import type { Imovel } from "./types";

export const imoveis: Imovel[] = [
  {
    id: 1,
    codigo: "001",
    titulo: "Apartamento de Alto Padrão à venda no Residencial Taij",
    finalidade: "venda",
    categoria: "Apartamento",
    cidade: "Porto União",
    bairro: "Centro",
    endereco: "Rua Visconde de Guarapuava, 110",
    quartos: 3,
    banheiros: 4,
    vagas: 2,
    area: 0,
    preco: 1800000,
    imagem: "/assets/images/fotos_apartamento_TAJI/001.jpg",
    imagens: [
      "/assets/images/fotos_apartamento_TAJI/001.jpg",
      "/assets/images/fotos_apartamento_TAJI/002.jpg",
      "/assets/images/fotos_apartamento_TAJI/003.jpg",
      "/assets/images/fotos_apartamento_TAJI/004.jpg",
      "/assets/images/fotos_apartamento_TAJI/005.jpg",
      "/assets/images/fotos_apartamento_TAJI/006.jpg",
      "/assets/images/fotos_apartamento_TAJI/007.jpg",
      "/assets/images/fotos_apartamento_TAJI/008.jpg",
      "/assets/images/fotos_apartamento_TAJI/009.jpg",
      "/assets/images/fotos_apartamento_TAJI/010.jpg",
      "/assets/images/fotos_apartamento_TAJI/011.jpg",
      "/assets/images/fotos_apartamento_TAJI/012.jpg",
      "/assets/images/fotos_apartamento_TAJI/013.jpg",
      "/assets/images/fotos_apartamento_TAJI/014.jpg",
      "/assets/images/fotos_apartamento_TAJI/015.jpg",
      "/assets/images/fotos_apartamento_TAJI/016.jpg",
      "/assets/images/fotos_apartamento_TAJI/017.jpg",
      "/assets/images/fotos_apartamento_TAJI/018.jpg"
    ],
    descricao:
      "Apartamento de alto padrão à venda no Residencial Taij, no Centro de Porto União. Localizado na Rua Visconde de Guarapuava, 110, este imóvel oferece sofisticação, conforto e excelente distribuição dos ambientes. \n São 03 suítes, sendo 01 suíte master com hidromassagem e closet, além de sala de estar e jantar em conceito aberto, cozinha, lavabo, área de serviço, churrasqueira e 02 vagas de garagem. \n O Residencial Taij também conta com uma estrutura pensada para proporcionar bem-estar e momentos especiais, oferecendo salão de festas com churrasqueira, espaço zen e cobertura. Uma excelente opção para quem deseja morar com exclusividade em uma das melhores localizações da cidade. \n Valor: R$ 1.800.000,00",
    destaque: true,
    comodidades: ["Churrasqueira"],
  },
  {
    id: 2,
    codigo: "002",
    titulo: "Apartamento moderno proximo a servicos",
    finalidade: "venda",
    categoria: "Apartamento",
    cidade: "Porto Uniao",
    bairro: "Sao Pedro",
    endereco: "Ruas novas existentes, 3455",
    quartos: 2,
    banheiros: 2,
    vagas: 1,
    area: 92,
    preco: 495000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Apartamento com acabamento contemporaneo, vaga de garagem e facil acesso ao centro comercial.",
    destaque: true,
  },
  {
    id: 3,
    codigo: "003",
    titulo: "Sala comercial para locacao no centro",
    finalidade: "locacao",
    categoria: "Comercial",
    cidade: "Uniao da Vitoria",
    bairro: "Centro",
    endereco: "Rua imaginaria, 321",
    quartos: 0,
    banheiros: 1,
    vagas: 0,
    area: 58,
    preco: 2800,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Ideal para escritorio ou atendimento, com excelente visibilidade e fluxo de pessoas.",
    destaque: true,
  },
  {
    id: 4,
    codigo: "004",
    titulo: "Terreno residencial em bairro tranquilo",
    finalidade: "venda",
    categoria: "Terreno",
    cidade: "Uniao da Vitoria",
    bairro: "Limeira",
    endereco: "Rua que nao existe, 987",
    quartos: 0,
    banheiros: 0,
    vagas: 0,
    area: 360,
    preco: 210000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Terreno plano, pronto para construir, em regiao com boa valorizacao e vizinhanca residencial.",
    destaque: true,
  },
  {
    id: 5,
    codigo: "005",
    titulo: "Casa para locacao com 2 quartos",
    finalidade: "locacao",
    categoria: "Casa",
    cidade: "Porto Uniao",
    bairro: "Santa Rosa",
    endereco: "Rua ficticia da mente, 321",
    quartos: 2,
    banheiros: 1,
    vagas: 1,
    area: 84,
    preco: 1900,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Casa funcional para o dia a dia, com patio frontal, lavanderia coberta e vaga descoberta.",
    destaque: true,
  },
  {
    id: 6,
    codigo: "006",
    titulo: "Apartamento compacto para locacao",
    finalidade: "locacao",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 1450,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
  {
    id: 7,
    codigo: "007",
    titulo: "Apartamento compacto para locacao",
    finalidade: "locacao",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 1450,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
  {
    id: 8,
    codigo: "008",
    titulo: "Apartamento compacto para venda",
    finalidade: "venda",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 145000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
  {
    id: 9,
    codigo: "009",
    titulo: "Apartamento compacto para locacao",
    finalidade: "locacao",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 1450,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
  {
    id: 10,
    codigo: "010",
    titulo: "Apartamento compacto para venda",
    finalidade: "venda",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 145000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
];
