import type { Imovel } from "./types";

export const imoveis: Imovel[] = [
  {
    id: 1,
    codigo: "001",
    titulo: "Casa com quintal e area gourmet",
    finalidade: "venda",
    categoria: "Casa",
    cidade: "Uniao da Vitoria",
    bairro: "Centro",
    endereco: "Rua imaginaria das maravilhas, 123",
    quartos: 3,
    banheiros: 2,
    vagas: 2,
    area: 186,
    preco: 780000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Casa ampla para familias que buscam localizacao central, ambientes integrados e espaco para receber visitas.",
    destaque: true,
  },
  {
    id: 2,
    codigo: "002",
    titulo: "Apartamento moderno proximo a servicos",
    finalidade: "venda",
    categoria: "Apartamento",
    cidade: "Porto Uniao",
    bairro: "Sao Pedro",
    endereco: "Ruas novas existentes, 3455",
    quartos: 2,
    banheiros: 2,
    vagas: 1,
    area: 92,
    preco: 495000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Apartamento com acabamento contemporaneo, vaga de garagem e facil acesso ao centro comercial.",
    destaque: true,
  },
  {
    id: 3,
    codigo: "003",
    titulo: "Sala comercial para locacao no centro",
    finalidade: "locacao",
    categoria: "Comercial",
    cidade: "Uniao da Vitoria",
    bairro: "Centro",
    endereco: "Rua imaginaria, 321",
    quartos: 0,
    banheiros: 1,
    vagas: 0,
    area: 58,
    preco: 2800,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Ideal para escritorio ou atendimento, com excelente visibilidade e fluxo de pessoas.",
    destaque: true,
  },
  {
    id: 4,
    codigo: "004",
    titulo: "Terreno residencial em bairro tranquilo",
    finalidade: "venda",
    categoria: "Terreno",
    cidade: "Uniao da Vitoria",
    bairro: "Limeira",
    endereco: "Rua que nao existe, 987",
    quartos: 0,
    banheiros: 0,
    vagas: 0,
    area: 360,
    preco: 210000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Terreno plano, pronto para construir, em regiao com boa valorizacao e vizinhanca residencial.",
    destaque: true,
  },
  {
    id: 5,
    codigo: "005",
    titulo: "Casa para locacao com 2 quartos",
    finalidade: "locacao",
    categoria: "Casa",
    cidade: "Porto Uniao",
    bairro: "Santa Rosa",
    endereco: "Rua ficticia da mente, 321",
    quartos: 2,
    banheiros: 1,
    vagas: 1,
    area: 84,
    preco: 1900,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Casa funcional para o dia a dia, com patio frontal, lavanderia coberta e vaga descoberta.",
    destaque: true,
  },
  {
    id: 6,
    codigo: "006",
    titulo: "Apartamento compacto para locacao",
    finalidade: "locacao",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 1450,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
  {
    id: 7,
    codigo: "007",
    titulo: "Apartamento compacto para locacao",
    finalidade: "locacao",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 1450,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
  {
    id: 8,
    codigo: "008",
    titulo: "Apartamento compacto para venda",
    finalidade: "venda",
    categoria: "Apartamento",
    cidade: "Uniao da Vitoria",
    bairro: "Nossa Senhora da Salete",
    endereco: "Rua das maravilhas, 123",
    quartos: 1,
    banheiros: 1,
    vagas: 1,
    area: 48,
    preco: 145000,
    imagem: "/assets/images/casa01.jpg",
    descricao:
      "Opcao pratica para quem busca mobilidade e baixo custo de manutencao em regiao consolidada.",
    destaque: true,
  },
];
